export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';
export const RESTAURANT_VOTE_SUCCESS = 'RESTAURANT_VOTE_SUCCESS';
export const RESTAURANT_VOTE_FAIL = 'RESTAURANT_VOTE_FAIL';
